name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false # checkout is needed to run the action of this repo, but it shouldn't conflict with the checkout in the semantic-release action itself.

      - name: Semantic Release
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
